AllCops:
  Exclude:
    - 'bin/bundle'
    - 'config/environments/*.rb'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - app/views/api/**/*